[pytest]
filterwarnings =
    ignore:.*iscoroutinefunction.*:DeprecationWarning
    ignore:.*datetime.datetime.utcnow.*:DeprecationWarning
    ignore:.*datetime.utcnow.*:DeprecationWarning
    ignore:.*cryptography.*:DeprecationWarning
    ignore:.*urllib3.*:DeprecationWarning
    ignore:.*pkg_resources.*:DeprecationWarning
